.github/workflows/python-publish.yml
README.rst
tox.ini

One rst syntax error stopped the release process.
To avoid this error in the future, I added a new tox environment to test the packaging process.
All steps to release a new bo4e package version are now described in the README.rst

Fix rst syntax error in README.rst

---

src/bo4e/com/adresse.py

If you set an attribute to `init=False` you will get an issue in the deserialisation process. The json which is created from an object which does not contain an optional attribute won't contain it. But during the deserialisation process **all** potential attributes are required to be there. So we set all optional attributes per default to None.

Change construction for optional attributes

---

src/bo4e/com/adresse.py
tests/test_adresse.py
tests/test_data/test_data_adresse/test_data_adresse_only_required_fields.json

Before strasse and hausnummer were required fields and postfach optional. Since postfach is an alternative address option to strasse and hausnummer this was changed to either strasse and hausnummer or postfach being a required address field.

🔨 Add postfach as alternative to strasse

---

src/bo4e/bo/geschaeftspartner.py
tests/test_geschaeftspartner.py

The BO4E standard does not define if partneradresse is optional or required for Geschaeftspartner. So we define partneradresse as optional until the BO4E standard defines the cardinality.

Make attribute partneradresse in Geschaeftspartner optional

---

LICENSE.rst
docs/conf.py

The year in the License was still 2020 in our BO4E documentation.
So this PR will fix this small issue

Update year for copyright in LICENSE and docs/conf.py

---

pyproject.toml
setup.cfg

I also added a marker to remove the warnings during tests caused by datafiles

🔧 Move pytest configs from setup.cfg to pyproject.toml

---

tox.ini

Noticed that the coverage only showed the tests.
Now the tests are ignored and the actual files are tested.

☂ Fix coverage

---

README.rst

This PR just adds a regular expression to the README.md.
With the help of this regex, you can just copy paste the enum entries from the bo4e docu and paste them into the regex101 page.

📝 Add regex to quickly add new enumerations from bo4e standard

---

setup.cfg

I am not totally sure when we got the UserWarnings caused by the dashed-seperated variable names in the `setup.cfg` file.
My best guess is the test for packaging `tox -e test_packaging`.
At least in the output of this command, I am not able to find these UserWarnings anymore.
This PR is related to the issue https://github.com/Hochfrequenz/BO4E-python/issues/55

🎨 Fix UserWarnings caused by usage of dash-separated names

---

.github/workflows/black.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.github/workflows/linting.yml
.github/workflows/python-publish.yml
.github/workflows/tests.yml

Rationale:
- The code formatter (black) needs to run only in 1 python version; use the latest one
- The tests should cover all versions >= 3.8 (min version)
- Other than the tests, the coverage measurement needs to happen only once; use the latest python version
- Linting only needs to be done the most recent version

👷 Test in Multiple Python Versions; Run Black, Coverage and Linter in most recent version only

---

src/bo4e/enum/anrede.py
src/bo4e/enum/strenum.py
tests/test_enums.py

I'd like to merge this already to see if the docs on https://bo4e-python.readthedocs.io/en/master/api/bo4e.enum.html#module-bo4e.enum.anrede show up after releasing this. It's a "testballon" ;)

🎈 Add Docstrings to Anrede Enum Members

---

docs/api/bo4e.enum.rst
src/bo4e/enum/anrede.py
src/bo4e/enum/strenum.py
tests/test_enums.py
tox.ini

The last approaches to have documented enum members (not only classes) on read the docs resulted in a heuristic trial and error development process (see #75).
Now here's the next step to ultimate documentation truth on how to _really_ do it (aka "richtig statt falsch"):
- instead of adding docstrings somewhen at runtime (#75), add docs at "compile" time instead
- use comments with `#:` prefix as decribed here https://github.com/sphinx-doc/sphinx/issues/3255
- test the docs _locally_ (instead of waiting for readthedocs to update) by running tox - docs and checking the HTML output in `.tox/docs/tmp/html`
Works on my machine:

📝Document Enum Members by using `#:`; Remove 🔥 DocStrEnum approach that turned out to not work

---

src/bo4e/com/zeitreihenwertkompakt.py
tests/test_zeitreihenwertkompakt.py

Implement COM Zeitreihenwertkompakt

---

src/bo4e/com/preis.py
tests/test_preis.py

Add COM Preis

---

src/bo4e/com/sigmoidparameter.py
src/bo4e/com/zeitreihenwertkompakt.py
tests/test_sigmoidparameter.py

Implement COM Sigmoidparameter

---

docs/api/bo4e.com.rst
src/bo4e/com/aufabschlagstaffelproort.py
tests/test_aufabschlagstaffelproort.py

Fixes https://github.com/Hochfrequenz/BO4E-python/issues/154

✨Add COM AufAbschlagstaffelProOrt

---

docs/api/bo4e.com.rst
src/bo4e/com/energieherkunft.py
src/bo4e/com/zeitreihenwertkompakt.py
tests/test_energieherkunft.py

Fixes https://github.com/Hochfrequenz/BO4E-python/issues/157

✨Add COM Energieherkunft

---

src/bo4e/com/standorteigenschaftenallgemein.py
tests/test_standorteigenschaftenallgemein.py

✨ Add COM StandorteigenschaftenAllgemein

---

src/bo4e/com/preisgarantie.py
tests/test_preisgarantie.py

beschreibung is an optional attribute in [Preisblatt](https://www.bo4e.de/dokumentation/komponenten/com-preisgarantie)

Make beschreibung optional (again)

---

docs/api/bo4e.com.rst
src/bo4e/com/aufabschlag.py
src/bo4e/com/preisstaffel.py
src/bo4e/validators.py
tests/test_aufabschlag.py

Fixes https://github.com/Hochfrequenz/BO4E-python/issues/141

✨Add COM AufAbschlag

---

setup.cfg

`attrs` is also what we refer to in the (unittested) requirements-files:
https://github.com/Hochfrequenz/BO4E-python/blob/c8f0c5fdc8287d13389550024b207ee3b953d8e8/requirements.in#L1

📦️ 🐛use attrs in setup.cfg (not attr)

---

src/bo4e/com/tagesvektor.py
tests/test_tagesvektor.py

Implement COM Tagesvektor

---

docs/api/bo4e.com.rst
src/bo4e/com/fremdkostenposition.py
src/bo4e/com/tagesvektor.py
src/bo4e/com/verbrauch.py
src/bo4e/validators.py
tests/test_fremdkostenposition.py

Implement COM Fremdkostenposition

---

src/bo4e/com/regionalepreisgarantie.py
tests/test_regionalepreisgarantie.py

https://www.bo4e.de/dokumentation/komponenten/com-regionalepreisgarantie

✨ Add COM RegionalePreisgarantie

---

pyproject.toml

as described here https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

🧑‍💻Harmonize isort and black via pyproject.toml

---

README.rst

because we're done with enums :)

Remove Enum Hint from README

---

src/bo4e/bo/preisblattkonzessionsabgabe.py
tests/test_preisblatt_konzessionsabgabe.py

Implement BO PreisblattKonzessionsabgabe

---

src/bo4e/bo/preisblattnetznutzung.py
tests/test_preisblattnetznutzung.py

Implement BO PreisblattNetznutzung

---

src/bo4e/bo/tarifkosten.py
tests/test_kosten.py
tests/test_tarifkosten.py

Implement BO Tarifkosten

---

src/bo4e/bo/preisblattmessung.py
tests/test_geraeteeigenschaften.py
tests/test_preisblatt_messung.py

Implement BO PreisblattMessung

---

.readthedocs.yaml

Add config file for readthedocs
To update Python version
To fix error message: "cannot import name 'Protocol' from 'typing'"

Fix readthedocs docs

---

src/bo4e/bo/geschaeftspartner.py

There was a small error in the pydantic rework, the attribute `kontaktweg` of the BO Geschaeftspartner was not optional like the [BO4E documentation](https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-geschaftspartner) says.
This PR fixes it

🎨 Make kontaktweg optional in BO Geschaeftsparter

---

src/bo4e/enum/sparte.py

https://www.bo4e.de/dokumentation/enumerations/enum-leistungstyp/23-2-2022
Ich weiß ehrlich gesagt nicht, warum wir das machen.

Extend ENUM Sparte: Add `STROM_UND_GAS`

---

src/bo4e/enum/geraetetyp.py

https://www.bo4e.de/dokumentation/enumerations/enum-geraetetyp/23-2-2022

Extend ENUM `Geraetetyp`: Add `EDL_40`

---

docs/api/bo4e.com.rst
src/bo4e/bo/buendelvertrag.py
src/bo4e/bo/vertrag.py
tests/test_buendelvertrag.py
tests/test_vertrag.py

Implemented `bo.Buendelvertrag`. [Current version](https://www.bo4e.de/dokumentation/geschaeftsobjekte/bo-buendelvertrag/02-03-2022)
Note: Since the new version of `bo.Buendelvertrag` have several similarities to `bo.Vertrag` the linter complained about duplicate code. So, don't wonder about the linter disable comment.
Resolves #416

Implement `bo.Buendelvertrag` and corresponding tests

---

json_schemas/bo/Buendelvertrag.json
json_schemas/bo/Kosten.json
json_schemas/bo/Tarifkosten.json
json_schemas/generate_json_schemas.py

(chore) Strip docstrings in autogenerated json schemas (Python 3.11)

---

src/bo4e/bo/geschaeftsobjekt.py
src/bo4e/com/com.py
tests/test_externe_referenz.py
tests/test_messlokation.py

This allows to deserialized unmatched properties

🐍 Add  Pydantic `extra="allow"` to Geschaeftsobjekt and COM base classes

---

docs/uml.py

This PR adds compatibility to add cardinalities not only to connection but to node fields. Also a bit redundance got removed. Before, fields which had connections to other nodes appeared in the field list too.
Here is a little example:
Old:
New:

Add cardinality to every field and remove redundance

---

docs/test_uml.py
docs/uml.py

This little feature replaces `ConstrainedStrValue` with `str<your regex pattern>`.
Example:

Show regex patterns in fields

---

tests/test_adresse.py
tests/test_geschaeftspartner.py

Replaces py imports in tests suit with pathlib

---

docs/requirements.txt
requirements.txt
src/bo4e/bo/messlokation.py
src/bo4e/com/adresse.py
src/bo4e/com/zeitraum.py
src/bo4e/validators.py
tests/test_preis.py
tests/test_tarifpreis.py

Review #483 first.
Resolves #480

Make validators more readable

---

tests/test_externe_referenz.py

fixes
> tests\test_externe_referenz.py:43: error: Unused "type: ignore" comment  [unused-ignore]
tests\test_externe_referenz.py:44: error: Unused "type: ignore" comment  [unused-ignore]
caused by unpinned dependencies #474

(chore) Remove unnecessary type ignore

---

.pylintrc
src/bo4e/bo/marktlokation.py
src/bo4e/bo/messlokation.py
tests/test_marktlokation.py
tests/test_messlokation.py

Fixes https://github.com/bo4e/BO4E-python/issues/532

fix: combination validation in Marktlokation

---

README.rst

The required python version is already part of the setup.cfg
https://github.com/bo4e/BO4E-python/blob/8772f8f9b6e306d3b44ee7ac34db0f379f625497/setup.cfg#L26

remove required python version in readme

---

src/bo4e/enum/anrede.py

https://github.com/bo4e/BO4E-python/issues/657
wie in dem Ticket #657  festgehalten wird in dem PR das ENUM Anrede erweitert um 
```python
FAMILIE = "FAMILIE"  #: Familie
ERBENGEMEINSCHAFT = "ERBENGEMEINSCHAFT"  #: Erbengemeinschaft
GRUNDSTUECKSGEMEINSCHAFT = "GRUNDSTUECKSGEMEINSCHAFT"  #: Grundstücksgemeinschaft
```
Der Wert `INDIVIDUELL` wurde entfernt.

657 Erweiterung des Enums `Anrede`

---

.github/workflows/dependabot_automerge.yml

This PR adds a GitHub Action which automatically approves the PRs of the Dependabot.
If all checks (unit tests, linter, etc) passed, the PR will automatically get merged.
This keeps the dependecies always up to date and saves a lot of repetitive work

💚 Add GH action to merge automatically dependabot PRs

---

docs/conf.py
docs/index.rst
docs/versioning.rst
src/bo4e/version.py

This PR fixes the circular import issue on read the docs and adds some details how we are versioning our standard.

📝 Fix Documentation Build on ReadTheDocs And Add Documentation About Versioning

---

.readthedocs.yaml

this PR should get merged after #673.
With the PR #673 the documentation will also get fixed.

⬆️ Bump os build version for read-the-docs

---

.github/workflows/python-publish-scheduled.yml
.github/workflows/python-publish.yml

here a linkt to check the cronjob: https://crontab.guru/#23_1_1_1/6_*
Merge #673 before this one.

💚 Add Schedule to Release on 01.01. and 01.06.

---

src/bo4e/enum/zaehlertyp.py

Dieser PR ergänzt den Namen Ferraris Zähler in der Dokumentation damit man es leichter zuordnen kann.

📝 improve documentation regarding Ferraris Zähler

---

.github/workflows/coverage.yml
.github/workflows/linting.yml
.github/workflows/python-publish.yml
pyproject.toml

the tests already run in python 3.12 for a while

ci/chore: Run entire CI in 3.12; mark package as 3.12 compatible

---

.github/dependabot.yml
.github/workflows/docs_latest.yml
.github/workflows/python-publish.yml

Version was upgraded by Dependabot in #767.

📍Pin version `sphinx-notes/pages@v2`

---

.github/workflows/docs_latest.yml
.github/workflows/python-publish.yml

When e.g. merging a PR, the docs /latest will be rebuild. But when you trigger a new release while the action is still running, the action to build docs for version X will fetch and checkout the gh-pages branch. One of the runs will then raise an error upon pushing.
To resolve these concurrency issues, GitHub provides a way to control it a bit: https://docs.github.com/en/actions/using-jobs/using-concurrency

💚Fix doc creation concurrency

---

src/bo4e/utils/__init__.py

Some descriptions had trailing whitespaces in JSON schemas.

🩹Strip descriptions

---

.github/workflows/python-publish.yml

Meine Idee war damals wohl, major bumps nur durch den cronjob zu erlauben. Naja, habs hiermit erstmal wieder erlaubt.

fix(versioning): 🩹Allow major bumps

---

.gitignore
docs/_static/css/colors.css
docs/_static/css/override.css
docs/changelog.rst
docs/conf.py

This also shows how to customize styling which may be helpful for later customizations.

docs: Improve readablity and styling of the compatibility matrix' legend
