README.rst, docs/api/bo4e.com.rst, requirements/base.txt, requirements/dev.txt, requirements/docs.txt, requirements/tests.txt, src/bo4e/bo/geschaeftsobjekt.py, src/bo4e/bo/marktlokation.py, src/bo4e/bo/marktteilnehmer.py, src/bo4e/com/externereferenz.py, tests/test_adresse.py, tests/test_externe_referenz.py, tests/test_geschaeftsobjekt.py, tests/test_marktteilnehmer.py, tox.ini
Add externereferenz component to bo4e python package
=> Introduce COM.ExterneReferenz (component, tests and documentation)

src/bo4e/bo/geschaeftspartner.py, src/bo4e/bo/marktlokation.py, src/bo4e/bo/marktteilnehmer.py, src/bo4e/com/adresse.py, src/bo4e/com/com.py, src/bo4e/com/externereferenz.py, src/bo4e/com/geokoordinaten.py, src/bo4e/com/katasteradresse.py, tests/test_adresse.py, tests/test_geokoordinaten.py, tests/test_geschaeftsobjekt.py, tests/test_marktlokation.py, tox.ini
To use these objects in SQL alchemy they have to be mutable
=> Remove "frozen=True" in the attr.s decorator of Business Objects

setup.cfg, tests/test_geschaeftspartner.py
Just small spelling corrections in setup.cfg and test_adresse.py
=> Fix small typos

README.rst
=> Add code style shield to README

.github/workflows/linting.yml, .github/workflows/tests.yml, .vscode/settings.json, docs/_static/bo4e-python-favicon.svg, pyproject.toml, src/bo4e/bo/geschaeftsobjekt.py, src/bo4e/bo/geschaeftspartner.py, src/bo4e/bo/marktlokation.py, src/bo4e/bo/marktteilnehmer.py, src/bo4e/cases.py, src/bo4e/com/adresse.py, src/bo4e/com/com.py, src/bo4e/com/externereferenz.py, src/bo4e/com/geokoordinaten.py, src/bo4e/com/katasteradresse.py, src/bo4e/com/messlokationszuordnung.py, src/bo4e/enum/landescode.py, tox.ini
I changed the tox config to a better understandable structure.
On this way, I also changed the linter from flake8 to pylint.
pylint seems to be stricter than flake8, therefore I had to add some docstrings and disable warnings.
Finally I sorted all imports with isort.
=> Clean up tox.ini

docs/api/bo4e.bo.rst, docs/api/bo4e.com.rst, docs/api/bo4e.enum.rst, src/bo4e/bo/messlokation.py, src/bo4e/com/dienstleistung.py, src/bo4e/com/hardware.py, src/bo4e/enum/dienstleistungstyp.py, src/bo4e/enum/geraetetyp.py, tests/test_messlokation.py
By adding the BO Messlokation (#44) I added also:
* enums: 
* Geraetetyp
* dienstleistungstyp
* components:
* Hardware
* Dienstleistung
=> ✨ Add BO Messlokation

README.rst
see https://github.com/Hochfrequenz/BO4E-python/tree/hf-kklein-patch-1#other-noteworthy-bo4e-implementations
=> Add list of other BO4E implementations to README

src/bo4e/enum/anrede.py, src/bo4e/enum/strenum.py, tests/test_enums.py
Co-authored-by: Kevin <68426071+hf-krechan@users.noreply.github.com>
=> 🔖 BO4E v0.0.14 (#75)

src/bo4e/com/marktgebietinfo.py, tests/test_marktgebietinfo.py
=> Add COM Marktgebietinfo

src/bo4e/com/zeitintervall.py, tests/test_zeitintervall.py
fixes https://github.com/Hochfrequenz/BO4E-python/issues/187
=> Add COM Zeitintervall

docs/api/bo4e.com.rst, docs/api/bo4e.enum.rst, src/bo4e/com/preisgarantie.py, tests/test_preisgarantie.py
Fixes: https://github.com/Hochfrequenz/BO4E-python/issues/163
=> ✨Add COM Preisgarantie

src/bo4e/com/tarifpreis.py, src/bo4e/com/zeitreihenwertkompakt.py, tests/test_tarifpreis.py
=> Add Tarifpreis COM

docs/api/bo4e.com.rst, src/bo4e/com/steuerbetrag.py, tests/test_steuerbetrag.py
Fixes https://github.com/Hochfrequenz/BO4E-python/issues/160
=> ✨Add COM Steuerbetrag

docs/api/bo4e.com.rst, src/bo4e/com/standorteigenschaftengas.py, tests/test_standorteigenschaftengas.py
fixes https://github.com/Hochfrequenz/BO4E-python/issues/209
=> Add COM StandorteigenschaftenGas

src/bo4e/com/kriteriumwert.py, src/bo4e/com/zeitreihenwertkompakt.py, tests/test_kriteriumswert.py
=> Implement COM KriteriumWert

src/bo4e/com/angebotsposition.py, src/bo4e/com/standorteigenschaftenallgemein.py, src/bo4e/com/standorteigenschaftengas.py, src/bo4e/com/zeitreihenwertkompakt.py, tests/test_angebotsposition.py, tests/test_standorteigenschaftengas.py
=> Implement COM Angebotsposition

src/bo4e/com/regionalegueltigkeit.py, tests/test_regionalegueltigkeit.py, tests/test_zeitreihenwert.py
fixes https://github.com/Hochfrequenz/BO4E-python/issues/151
=> Implement COM RegionaleGueltigkeit

src/bo4e/com/preisstaffel.py, src/bo4e/com/sigmoidparameter.py, tests/test_energieherkunft.py, tests/test_preisstaffel.py, tests/test_sigmoidparameter.py
=> Implement COM Preisstaffel

src/bo4e/com/geraeteeigenschaften.py, tests/test_geraeteeigenschaften.py
=> Implement COM Geraeteeigenschaften

docs/api/bo4e.com.rst, src/bo4e/com/geraet.py, tests/test_geraet.py
Fixes https://github.com/Hochfrequenz/BO4E-python/issues/256
=> ✨Add COM Geraet

src/bo4e/com/ausschreibungsdetail.py, tests/test_adresse.py, tests/test_ausschreibungsdetail.py, tests/test_enums.py, tests/test_menge.py, tests/test_zeitraum.py
=> Implement COM Ausschreibungsdetail

docs/api/bo4e.com.rst, src/bo4e/com/tarifeinschraenkung.py, tests/test_tarifeinschraenkung.py
Fixes https://github.com/Hochfrequenz/BO4E-python/issues/162
=> ✨Add COM Tarifeinschraenkung

docs/api/bo4e.com.rst, src/bo4e/com/positionsaufabschlag.py, tests/test_positionsaufabschlag.py
Fixes https://github.com/Hochfrequenz/BO4E-python/issues/150
=> ✨ Add COM PositionsAufAbschlag

src/bo4e/com/verbrauch.py, src/bo4e/com/zeitreihenwert.py, src/bo4e/validators.py, tests/test_verbrauch.py
review #268 first to fix the mypy check
fixes #178
=> Implement COM Verbrauch

docs/api/bo4e.com.rst, src/bo4e/com/aufabschlagregional.py, tests/test_aufabschlagregional.py, tox.ini
Fixes https://github.com/Hochfrequenz/BO4E-python/issues/169
=> ✨ Add COM AufAbschlagregional

src/bo4e/com/tarifpreisposition.py, tests/test_tarifpreisposition.py
https://www.bo4e.de/dokumentation/komponenten/com-tarifpreisposition
fixes #176
=> ✨ Introduce Tarifpreisposition

src/bo4e/com/regionalepreisstaffel.py, tests/test_fremdkostenposition.py, tests/test_preisstaffel.py, tests/test_regionalepreisstaffel.py
Fixes #152
very similar to #183 
⚠️ before merging to main please update the dependent branch of #293 with changes
=> Implement COM RegionalePreisstaffel

src/bo4e/com/angebotsvariante.py, tests/test_angebotsteil.py, tests/test_angebotsvariante.py, tests/test_betrag.py
=> Implement COM Angebotsvariante

src/bo4e/com/tarifberechnungsparameter.py, src/bo4e/com/tarifpreis.py, tests/test_preis.py, tests/test_tarifberechnungsparameter.py, tests/test_tarifpreis.py
Fixes #186
https://www.bo4e.de/dokumentation/komponenten/com-tarifberechnungsparameter
=> Implement COM Tarifberechnungsparameter

docs/requirements.in, docs/requirements.txt, requirements.in, requirements.txt, setup.cfg
=> ➖ remove stringcase dependency

docs/conf.py, docs/uml.py, src/bo4e/com/com.py
Adds enum relations into the UML graphs for `bo` and `com` classes.
Also a little fix for the linter in `COM`.
Resolves #399
=> Add Enums into UML graphics

src/bo4e/enum/leistungstyp.py
https://www.bo4e.de/dokumentation/enumerations/enum-leistungstyp/23-2-2022
=> Extend ENUM `Leistungstyp`: Add `DIENSTLEISTUNG`

src/bo4e/bo/regionaltarif.py
=> Add Docstring to class `bo.Regionaltarif`

docs/uml.py, tests/serialization_helper.py, tests/test_adresse.py, tests/test_geschaeftspartner.py
=> 🐍MyPy: Ignore import from `py._path`; harmonize type hints and default values

tests/test_bypassing_validation.py
no code changes in bo4e, just tests
credits to @lord-haffi
=> 🐍 Add example test on how to instantiate _without_ required attributes

tox.ini
prevents  error: INTERNAL ERROR -- Please try using mypy master on GitHub
=> (chore)📍Pin mypy version to 1.3.0

requirements.in, setup.cfg
(because moving to v2 requires some modifications)
https://docs.pydantic.dev/2.0/migration/
=> 📍Pin pydantic to v1.x

src/bo4e/bo/messlokation.py, src/bo4e/validators.py
=> Change `ModelAfterValidator` -> `ModelBeforeValidator`

.github/workflows/python-publish.yml
=> 📝 remove wrong information

generate_or_validate_json_schemas.py
Same as #692 but for the legacy branch.
=> Better JSON-Schema output for `Decimal`

docs/versioning.rst
This PR brings just the correct order in the documentation.
It follows the order of our version
=> 📝 Improve the order of functional and technical changes

.github/dependabot.yml, .github/workflows/docs_latest.yml, .github/workflows/python-publish.yml
Dependabot bump #770
First try to fix it #768
Maybe Dependabot doesn't like the Syntax of the version here. However, we don't need to update the action.
=> 🩹📍Pin `sphinx-notes/pages@v2` again

.github/dependabot.yml, .github/workflows/docs_latest.yml, .github/workflows/python-publish.yml
=> 📍Pinning again. Don't ask.

.pre-commit-config.yaml, src/bo4e/bo/geschaeftsobjekt.py, src/bo4e/bo/marktlokation.py, src/bo4e/bo/zaehler.py, src/bo4e/com/com.py, src/bo4e/com/rechnungsposition.py, src/bo4e/com/regionalegueltigkeit.py, src/bo4e/com/regionskriterium.py, src/bo4e/com/zaehlwerk.py
As suggested by @hf-kklein in #790 in an extra PR here
=> ⬆️Bump pre-commit black version

src/bo4e/enum/mengeneinheit.py
fixes #755 
fixes #756 
fixes #757
=> Add enum values for mengeneinheit

.github/workflows/docs_latest.yml, .github/workflows/test_docs.yml, docs/compatibility/__main__.py, docs/compatibility/diff.py, docs/compatibility/loader.py, docs/compatibility/versioning.py
I had to move some functions around due to circular import issues.
Resolves #785
=> 👷‍♂️Include only functional releases into compatibility matrix

docs/compatibility/versioning.py
There was a logical issue with the previous one. I added a little Unittest (not in CI) to test it locally.
Since all these tools have become more or less complex it may make sense to create a new Repo for it. But not for this PR.
=> 💚🩹Fix total ordering of `Version`

.gitignore, docs/changelog.rst, docs/compatibility/matrix.py, docs/conf.py
=> 📄Make compatibility matrix downloadable

bo4e_schemas_create_release.py
Fixes #731 
Testet here https://github.com/bo4e/BO4E-Schemas/releases/tag/v202401.1.2-rc15
=> 🩹Fix release creation on publish - don't set always as latest release

src/bo4e/utils/__init__.py
=> chore: Remove `print` for undocumend fields

src/bo4e/enum/lokationstyp.py
=> Add NELO and TR to Lokationstyp enum

README.rst
hoffe, das hilft euch und weiteren lesern weiter! merci
=> edit link to contribution as in #828

src/bo4e/com/preisstaffel.py, tests/test_preisstaffel.py
=> 738 add artikel id to preisstaffel
